name = "ForecastAccuracy"
uuid = "b9d94c12-295a-11ea-066b-bff6e5bc6a33"
authors = ["Guilherme Bodin <guilherme.b.moraes@gmail.com>"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "~1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]